### PR TITLE
Add Nix flake

### PR DESCRIPTION
**Pull request by ilkecan**
I believe the documentation introduced with [this commit](https://github.com/Sambruk/EgilSCIM/commit/fb918da03f6f21e64283d41ef99b97ca7ecf2bcd) should be helpful to understand  what is added.

To summarize, [Nix](https://nixos.org/) is a cross-platform package manager. It could build and test packages without an external dependency by managing everything itself. Flakes are a relatively new Nix feature that improves reproducibility, composability and usability in the Nix ecosystem[^1]. The things flake can be used include but not limited to build packages, run tests, create development environments or NixOS modules[^2]. The one added with this PR includes the first three (so, no NixOS module).

I don't want to repeat everything about Nix or Flakes. I think it would be better if I could answer your questions instead.

[^1]: https://www.tweag.io/blog/2020-05-25-flakes/
[^2]: https://nixos.wiki/wiki/Flakes#Output_schema

### CODE REVIEW

**Comment by ilkecan** [comment]
There was initially +85 commits, but I tried to squash them to reduce the number. But I am not sure how useful the information in a single commit after squashing them. So you may want to further squash them to a single commit before merging.

**Comment by ilkecan** [comment]
I created [this branch](https://github.com/ngi-nix/EgilSCIM/tree/flake-only) to make the flake usable outside the source repository. While I am willing to to further work on this until it is in an acceptable state, the current effort will not be wasted if this PR is not accepted.

**Comment by joesiltberg** [comment]
@ilkecan thank you for this contribution!

Sorry I haven't had time to look at it yet, I'll try to get around to it soon!

**Comment by joesiltberg** [comment]
@ilkecan do you consider this finished and ready for merge?

**Comment by ilkecan** [comment]
@joesiltberg It should be but I will go over it again and see if there is anything I can improve. I will get back to you in a couple of days.

**Comment by ilkecan** [comment]
@joesiltberg I refactored a couple of things using things I have learned since then and then squashed the commits.

I want to summarize what this PR is again. Nix is a platform agnostic package manager with very nice properties. This PR adds Nix expressions (build instructions) for various things (SCIM client, test server, test suite, development environment, tools and the example plugin). 

There are mainly two target groups for these derivations: you, as a developer and the users of this project. If you want to utilize Nix during development, then these Nix expressions would be most valuable inside the main repository. But if you don't consider using Nix, these Nix expressions probably don't need to be inside the main repository. They can be in a different repository and the interested parties can still build this project using those.

**Comment by joesiltberg** [comment]
Thank you for your contribution @ilkecan ! Sorry for the late merge.

**Pull request merged**
